version: "3.9"
services:
  exchange:
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    ports:
      - "8001:5001"
  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8002:5002"
  wallet:
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
